title: Antonino DiMaggio
description: Blog documenting my thoughts on machine learning, renewable energy, and everything in between.
url: "http://antoninodimaggio.com"
author: Antonino DiMaggio
name: Antonino DiMaggio
permalink: /:title:output_ext

# build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag

# files that should not be _site
exclude:
  - Gemfile
  - Gemfile.lock

# markdown to html
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# jekyll seo
twitter:
  username: tonyjdimaggio
  card: summary

card_image: /assets/images/profile_photo_twitter.jpg

social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/tonyjdimaggio"
    - "https://www.linkedin.com/antoninodimaggio"
    - "https://github.com/antoninodimaggio"

logo: /assets/images/profile_photo.jpg
image: /assets/images/profile_photo.jpg

# minify css
sass:
  style: compressed

# minify html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
  blanklines: false
  profile: false
  startings: [html, head, body]
